/// Generated by AssetsRefGenerator on 2021/05/03
export './extension.dart';

class R {
  /// This `R.image` struct is generated, and contains static references to static non-svg type image asset resources.
  static const image = _R_Image();
  static const anim = _R_Anim();
  static const json = _R_Json();
  static const i18n = _R_I18n();
}

class _R_Image {
  const _R_Image();

  final String action_delete = "assets/image/action_delete.png";
  final String action_report = "assets/image/action_report.png";
  final String loading_request = "assets/anim/loading_request.json";
  final String share_pyq = "assets/image/share_pyq.png";
  final String share_qq = "assets/image/share_qq.png";
  final String share_weibo = "assets/image/share_weibo.png";
  final String share_weixin = "assets/image/share_weixin.png";
}

class _R_Anim {
  const _R_Anim();
}

class _R_Json {
  const _R_Json();
}

class _R_I18n {
  const _R_I18n();
}