/// Generated by AssetsRefGenerator on ${.now?string("yyyy-MM-dd HH:mm")}
import 'package:flutter/material.dart';
import 'package:lottie/lottie.dart';

class R {
  /// This `R.image` struct is generated, and contains static references to static image asset resources.
  static const String package = "${extra[0]!}";
  static const image = _R_Image();
  static const anim = _R_Anim();
  static const json = _R_Json();
  static const i18n = _R_I18n();
}

extension StringExtension on String {
  Widget toImage({
    Key key,
    double scale,
    double width,
    double height,
    Color color,
    BoxFit fit = BoxFit.contain,
    AlignmentGeometry alignment = Alignment.center,
    String package = R.package,
  }) {
    return Image.asset(
      this,
      key: key,
      scale: scale,
      width: width,
      height: height,
      color: color,
      fit: fit,
      alignment: alignment,
      package: package,
    );
  }

  Widget toLottie({
    Key key,
    double width,
    double height,
    BoxFit fit = BoxFit.contain,
    Alignment alignment = Alignment.center,
    String package = R.package,
  }) {
    return Lottie.asset(
      this,
      key: key,
      width: width,
      height: height,
      fit: fit,
      alignment: alignment,
      package: package,
    );
  }
}

class _R_Image {
  const _R_Image();

  final String action_delete = "assets/image/action_delete.png";
}

class _R_Anim {
  const _R_Anim();
}

class _R_Json {
  const _R_Json();
}

class _R_I18n {
  const _R_I18n();
}