/// Generated by Flutter GetX Starter on ${.now?string("yyyy-MM-dd HH:mm")}
import 'dart:io';

extension FontWeightExtension on FontWeight {
  FontWeight get auto {
    if (Platform.isAndroid && this == FontWeight.bold) {
      return FontWeight.w500;
    }
    return this;
  }
}
