/// Generated by Flutter GetX Starter on ${.now?string("yyyy-MM-dd HH:mm")}
import './utils/http.dart';

class Api {
  /// 获取播放token
  static Future<dynamic> getVODPlayAuth(fileId) async {
    Map data = await Http.get(
      "/plat-zqa-server/storage/0.1.0/getVODPlayAuth",
      params: {"fileId": fileId},
    );
    return data;
  }
}
