/// Generated by Flutter GetX Starter on ${.now?string("yyyy-MM-dd HH:mm")}
import 'package:get/get.dart';

class Routes {
  static const HOME = '/home';

  static final routes = [
    // GetPage(
    //   name: Routes.HOME,
    //   page: () => HomeView(),
    //   binding: HomeBinding(),
    // ),
  ];
}