/// Generated by Flutter GetX Starter on ${.now?string("yyyy-MM-dd HH:mm")}
import './utils/http.dart';

class Api {
  static Future<dynamic> getHome(test) async {
    Map data = await Http.get(
      "/example/home/0.1.0/getHome",
      params: {"test": test},
    );
    return data;
  }
}
