/// Generated by Flutter GetX Starter on ${.now?string("yyyy-MM-dd HH:mm")}
import 'package:get/get.dart';

import '${usePrefix?string(Utils.toUnderline(name!)+'_','')}logic.dart';

class ${name!}Binding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<${name!}Logic>(
      () => ${name!}Logic(),
    );
  }
}
