/// Generated by Flutter GetX Starter on ${.now?string("yyyy-MM-dd HH:mm")}
import 'package:get/get.dart';

<#if defaultMode>
import '${usePrefix?string(Utils.toUnderline(name!)+'_','')}state.dart';
</#if>

class ${name!}Logic extends GetxController {
<#if defaultMode>
  final state = ${name!}State();
</#if>

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}
